apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-mvp
spec:
  license:
    accept: true
    license: L-APIG-BM7GDH
    use: NonProduction
  queueManager:
    mqsc:
    - configMap:
        items:
        - qminit.mqsc
        name: qm-configurations
    name: QM_MVP
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
      - env:
        - name: MQSNOAUT
          value: 'yes'
        name: qmgr
  version: 9.2.2.0-r1
  web:
    enabled: true
